language: go

# Debian Jessie has Go 1.3.3, Fedora 22 has Go 1.4.3,
# Fedora 23 has Go 1.5.1
go:
  - 1.3.3
  - 1.4.3
  - 1.5.1
  - 1.6
  - tip

install:
  - go get .

# Travis does not support FUSE, so we can't just run "./test.bash"
# Go 1.3.3 does not support testing.M, so skip the tests there.
script:
  - openssl version
  - go build
  - ./build.bash
  - if ! go version | grep go1.3.3 ; then go test ./internal/... ; fi
  - mkdir /tmp/cipherdir /tmp/mnt
  - echo 'pass' | gocryptfs -init /tmp/cipherdir
  - echo 'pass' | gocryptfs /tmp/cipherdir /tmp/mnt
  - echo 'bar' > /tmp/mnt/foo
  - fusermount -u /tmp/mnt
  - ls /tmp/cipherdir

sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo /bin/sh -c 'echo user_allow_other > /etc/fuse.conf'
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
    #  - sudo apt-get install -qq build-essential uuid-dev xfslibs-dev attr-dev acl-dev dmapi-dev
    #  - git clone https://github.com/rfjakob/fuse-xfstests /tmp/fuse-xfstests
    #  - cd /tmp/fuse-xfstests && make && cd -
